# Generated by Django 4.2.6 on 2023-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('inscricao_municipal', models.CharField(max_length=50)),
                ('indicacao_fiscal', models.CharField(max_length=50)),
            ],
        ),
    ]
