# Generated by Django 4.2.6 on 2023-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField()),
                ('contribuinte', models.IntegerField()),
                ('numero_identificacao', models.IntegerField()),
            ],
        ),
    ]
