# Generated by Django 4.2.6 on 2023-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carros',
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='indicacao_fiscal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='inscricao_municipal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pets',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pets',
            name='tamanho',
            field=models.CharField(max_length=100),
        ),
    ]
