# Generated by Django 4.2.6 on 2023-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_carros_alter_contribuinte_indicacao_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='idade',
            field=models.CharField(max_length=100),
        ),
    ]
