# Generated by Django 4.2.6 on 2023-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pets_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
