# Generated by Django 4.2.6 on 2023-10-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pets_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuinte',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
