# Generated by Django 4.2.6 on 2023-10-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_contribuinte_cpf_alter_contribuinte_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='contribuinte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contribuinte'),
        ),
    ]
