# Generated by Django 4.2.6 on 2023-10-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pets_contribuinte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuinte',
            name='complemento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='indicacao_fiscal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='inscricao_municipal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribuinte',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='numero_identificacao',
            field=models.CharField(max_length=50),
        ),
    ]
