# Generated by Django 4.2.6 on 2023-11-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contribuinte_complemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio_contri_pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('inscricao_municipal', models.CharField(max_length=50)),
                ('indicacao_fiscal', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=150)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('tamanho', models.CharField(max_length=100)),
                ('numero_identificacao', models.CharField(max_length=50)),
                ('contribuinte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contribuinte')),
            ],
        ),
    ]
