# Generated by Django 4.2.6 on 2023-11-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_relatorio_contri_pets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatorio_contri_pets',
        ),
    ]
